# Sample Reusable Workflow for building a React app
on:
  workflow_call:
    inputs:
      project:
        required: true
        type: string
    secrets:
      token:
        required: true
        
jobs:
  echo:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo "Hello this is a workflow to build and deploy the ${{ inputs.project }} React application"
